[package]
name = "sift"
version = "0.1.0"
description = "Local sample manager for producers"
authors = ["Jeroen Meijer"]
edition = "2021"
rust-version = "1.86.0"

[lib]
name = "sift_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1.53.1", features = ["full"] }
thiserror = "2.0.20"
anyhow = "1.0.104"
uuid = { version = "1.20.0", features = ["v4"] }
chrono = { version = "0.4.45", features = ["serde"] }
directories = "6.0.0"
tauri-plugin-dialog = "2.7.3"
walkdir = "2.5.0"
globset = "0.4.19"
symphonia = { version = "0.6.1", features = ["all"] }
cpal = "0.18.2"
hound = "3.5.1"
rtrb = "0.4.0"
tauri-plugin-drag = "2"
drag = "2.1.1"
stratum-dsp = "1.0.0"
notify = "8.2.0"
notify-debouncer-full = "0.7.0"
diesel = { version = "2.2.12", features = ["sqlite", "returning_clauses_for_sqlite_3_35", "chrono"] }
diesel_migrations = { version = "2.2.0", features = ["sqlite"] }
libsqlite3-sys = { version = "0.38.2", features = ["bundled"] }

[profile.release]
codegen-units = 1
lto = true
opt-level = 3
panic = "abort"
strip = true
